spring:
  profiles:
    active: dev

  application:
    name: spring-restful-api

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://10.32.66.1:3306/spring_restful_api
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "https://spring.cyberpond.online/login/oauth2/code/google"
            scope:
              - email
              - profile


custom:
  jwt:
    access-token:
      base64-secret: +jqkXG1TXntZHehg1GUQBRTwiqxRkU3Qq7moJQbmjuI=
      validity-in-seconds: 86400
    refresh-token:
      validity-in-seconds: 8640000

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: 0

logging:
  level:
    org.springframework.security: DEBUG

spring-boot-log: spring-boot-logs

server:
  forward-headers-strategy: framework